version: "3"
services:
    redis:
        image: 'redis:5.0.3'
        restart: always
        hostname: redis1
        container_name: redis1
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis_data/:/data/
    judge_server2:
        image: hwz634473223/judge_server:local
        restart: always
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        depends_on:
          - redis
        tmpfs:
            - /tmp
        volumes: 
            - $PWD:/RJudgeServer/
        environment:
            - WEB_SOCKET_URL=ws://192.168.31.129:9502/websocket/judge
            - TOKEN=12345
            - SERVER_URL=192.168.31.129:9501
        tty: true