version: "3"
services:
    judge_server2:
        image: hwz634473223/judge_server:local
        restart: always
        tmpfs:
            - /tmp
        volumes: 
            - ./:/RJudgeServer/
        environment:
            - WEB_SOCKET_URL=ws://echo.nwanna.cn
            - TOKEN=bf40718424b279059532d5bb2df67e64
            - NAME=HSYik8JESjHc5ZC
            - SERVER_URL=nwanna.cn
        working_dir: "/RJudgeServer"
        # entrypoint: ["python3","app/Server.py"]
        tty: true
