version: "3"
services:
    redis:
        image: 'redis:5.0.3'
        restart: always
        hostname: redis
        container_name: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis_data/:/data/
    judge_server1:
        image: hwz634473223/judge_server
        restart: always
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        depends_on:
          - redis
        tmpfs:
            - /tmp
        volumes: 
            - ./test_cases:/JudgeServer/test_cases
            - ./submissions:/JudgeServer/submissions
            - ./setting.json:/JudgeServer/app/setting.json
        environment:
            - WEB_SOCKET_URL=ws://api.nwanna.cn:801/websocket/judge
            - TOKEN=12345
            - SERVER_URL=nwanna.cn
        tty: true