version: "2"
services:
    judge_server1:
        image: hwz634473223/judge_server:local
        restart: always
        tmpfs:
            - /tmp
        volumes: 
            - ./:/RJudgeServer/
        environment:
            - WEB_SOCKET_URL=ws://172.17.0.1:1215
            - TOKEN=40780e9dc22544105ebb9bd74e71d4a4
            - NAME=2QssCtKQCGqxL4V
            - SERVER_URL=172.17.0.1:1215
        working_dir: "/RJudgeServer"
        entrypoint: ["python3","app/Server.py"]
        tty: true
    judge_server2:
        image: hwz634473223/judge_server:local
        restart: always
        tmpfs:
            - /tmp
        volumes: 
            - ./:/RJudgeServer/
        environment:
            - WEB_SOCKET_URL=ws://172.17.0.1:1215
            - TOKEN=40780e9dc22544105ebb9bd74e71d4a4
            - NAME=2QssCtKQCGqxL4V
            - SERVER_URL=172.17.0.1:1215
        working_dir: "/RJudgeServer"
        entrypoint: ["python3","app/Server.py"]
        tty: true
    
