version: "3"
services:
    judge_server2:
        image: hwz634473223/judge_server:local
        restart: always
        tmpfs:
            - /tmp
        volumes: 
            - ./:/RJudgeServer/
        environment:
            - WEB_SOCKET_URL=ws://homestead.test:1215
            - TOKEN=5b4bc9dc841e373db33348efd266868b
            - NAME=GeHOjRluUMKSYOk
            - SERVER_URL=homestead.test:1215
        working_dir: "/RJudgeServer"
        # entrypoint: ["python3","app/Server.py"]
        tty: true
